#!/usr/bin/env python3
"""Pack the local art-hash JSONL into the small offline Android index.

The input is generated by art_hash_poc.py. No reference JPEGs are bundled.
Format v1: b'AHI1', big-endian u32 row count, then for each row two u64
hashes, a 16-byte card UUID and u8 face (255=none, 0/1=face), a 16-byte
illustration UUID (all zero when absent), and UTF-8 name/set/collector with u16/u8/u8 byte-length
prefixes respectively. The Android reader validates the header.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import struct
import uuid


MAGIC = b"AHI1"
FACE_KEY = re.compile(r"^([0-9a-f-]{36})-([01])$")


def encoded(value: str, max_length: int, field: str) -> bytes:
    data = value.encode("utf-8")
    if len(data) > max_length:
        raise ValueError(f"{field} supera {max_length} bytes: {value!r}")
    return data


def build(source: Path, target: Path) -> int:
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".part")
    count = 0
    try:
        with source.open(encoding="utf-8") as rows, temporary.open("wb") as output:
            output.write(MAGIC + struct.pack(">I", 0))
            for line in rows:
                row = json.loads(line)
                name = encoded(row["name"], 65535, "name")
                set_code = encoded(row["set"], 255, "set")
                collector = encoded(row["collector_number"], 255, "collector_number")
                output.write(struct.pack(
                    ">QQ", int(row["phash"], 16), int(row["dhash"], 16)
                ))
                key = row["key"]
                face_key = FACE_KEY.fullmatch(key)
                output.write(uuid.UUID(face_key.group(1) if face_key else key).bytes)
                output.write(bytes((int(face_key.group(2)) if face_key else 255,)))
                illustration_id = row["illustration_id"]
                output.write(uuid.UUID(illustration_id).bytes if illustration_id else bytes(16))
                output.write(struct.pack(">H", len(name)) + name)
                output.write(bytes((len(set_code),)) + set_code)
                output.write(bytes((len(collector),)) + collector)
                count += 1
            output.seek(len(MAGIC))
            output.write(struct.pack(">I", count))
        temporary.replace(target)
    finally:
        temporary.unlink(missing_ok=True)
    print(f"{count:,} artes; {target.stat().st_size:,} bytes -> {target}")
    return count


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="hashes.jsonl")
    parser.add_argument("--output", type=Path, required=True, help="art_hash_index.bin")
    args = parser.parse_args()
    build(args.input, args.output)


if __name__ == "__main__":
    main()
